#Minecraft server properties
#Fri Jun 11 22:19:26 CST 2021
max-tick-time=2147483647
generator-settings={"landScheme"\:"vanilla","tempScheme"\:"random","rainScheme"\:"random","biomeSize"\:"medium","amplitude"\:1.0,"generateBopOre"\:true,"generatePoisonIvy"\:true,"generateBerryBushes"\:true,"generateThorns"\:true,"generateQuicksand"\:true,"generateLiquidPoison"\:true,"generateHotSprings"\:true,"generateNetherHives"\:true,"generateEndFeatures"\:true,"mainNoiseScaleX"\:80.0,"mainNoiseScaleY"\:160.0,"mainNoiseScaleZ"\:80.0,"coordinateScale"\:684.412,"heightScale"\:684.412,"upperLimitScale"\:512.0,"lowerLimitScale"\:512.0}
force-gamemode=false
allow-nether=true
gamemode=0
broadcast-console-to-ops=true
enable-query=false
player-idle-timeout=0
difficulty=3
spawn-monsters=true
op-permission-level=3
pvp=true
snooper-enabled=true
level-type=BIOMESOP
hardcore=false
enable-command-block=true
max-players=20
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=25565
server-ip=
spawn-npcs=true
allow-flight=true
level-name=GreedyCraft_world
view-distance=6
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
online-mode=true
max-build-height=256
level-seed=
prevent-proxy-connections=false
motd=A GreedyCraft Server
enable-rcon=false
defaultworldgenerator-port=
