name = "GreedyCraft"
author = "TCreopargh"
version = "1.38.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e087c908680879271e470023e9d8e8636bfb3fa50642f9d9a77ddc3ef2ee540"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
quilt = "0.17.0"

[export]
[export.curseforge]
project-id = 0
