name = "GreedyCraft"
author = "TCreopargh"
version = "1.38.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3b0d445af2d7ed99f1aa58d3a77a665264b46b78e2e27b777a555ee8413dc54"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
quilt = "0.17.0"

[export]
[export.curseforge]
project-id = 0
